basePath: /
definitions:
  models.User:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: ibrahima.coulibaly@etu.uca.fr
    name: Ibrahima Coulibaly
  description: API to manage users.
  title: Projet_Middleware/User
  version: 1.0.0
paths:
  /users:
    get:
      description: Get users.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Something went wrong
      summary: Get users.
      tags:
      - users
    post:
      description: Create a new user.
      parameters:
      - name: user
        in: body
        description: The user object to be created
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Something went wrong
  /users/{id}:
    get:
      description: Get a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get a user.
      tags:
      - users
    put:
      description: Update a specific user by ID.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      - name: user
        in: body
        description: Updated user data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Update a specific user by ID.
      tags:
      - users
    delete:
      description: Delete a specific user by ID.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Delete a specific user by ID.
      tags:
      - users
schemes:
- http
swagger: "2.0"
